<?php
$this->htmlElement('body')->appendAttribute('class', 'fromclassicwithlove jobs undo');
$escape = $this->plugin('escapeHtml');

?>

<?php echo $this->pageTitle($this->translate('Past Imports'), 1, $this->translate('FromClassicWithLove')); ?>
<?php if(empty($imports)): ?>

<?php else: ?>
<?php echo $this->pagination(); ?>

<form method='POST'>
    <fieldset id='page-actions'>
        <input type="submit" value="<?php echo $escape($this->translate('Submit')); ?>" />
    </fieldset>
    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
            <tr>
                <th><?php echo $escape($this->translate('Undo'));?></th>
                <th>
                    <?php echo $this->sortLink($escape($this->translate('Date')), 'id');?>
                </th>
                <th><?php echo $escape($this->translate('Action'));?></th>
                <th><?php echo $escape($this->translate('Result'));?></th>
                <th><?php echo $escape($this->translate('Status'));?></th>
                <th><?php echo $escape($this->translate('Owner'));?></th>
                <th><?php echo $escape($this->translate('Update')); ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($imports as $import): ?>
        <?php $job = $import->job(); ?>
        <?php $undoJob = $import->undoJob(); ?>
        <?php $jobArgs = $job->args(); ?>
        <?php $isUpdate = @$jobArgs['update'] == '1'; ?>
        <tr class="<?php echo $undoJob ? 'undone' : ''; ?>" >
            <td>
                <input type="checkbox" name="jobs[]" value="<?php echo $job->id(); ?>"<?php if ($isUpdate || $undoJob) echo ' disabled="disabled"'; ?>/>
            </td>
            <td>
                <?php echo $escape($this->i18n()->dateFormat($job->started())); ?>
            </td>
            <td>
                <span class="from-classicwith-love-action">
                    <?php echo $escape(ucfirst($this->translate($isUpdate ? 'update' : 'import'))); ?>
                </span>
                <br />
                <span class="from-classicwith-love-job-param">
                    <?php echo $this->hyperlink($this->translate('Job details'), $this->url('admin/id', ['controller' => 'job', 'action' => 'show', 'id' => $job->id()])); ?>
                </span>
                <?php if ($job->log()): ?>
                /
                <span class="from-classicwith-love-job-log">
                    <?php echo $this->hyperlink($this->translate('Log'), $this->url('admin/id', ['controller' => 'job', 'action' => 'log', 'id' => $job->id()]), ['target' => '_blank']); ?>
                </span>
                <?php endif; ?>
            </td>
            <td>
                <ul>
                <?php foreach ($import->stats() as $statsName => $stat): ?>
                    <?php
                        if ($statsName == 'item_sets') {
                            $statsName = $this->translate('item sets');
                        }
                        else if ($statsName == 'media') {
                            $statsName = $this->translate('media');
                        }
                        else if ($statsName == 'items') {
                            $statsName = $this->translate('items');
                        }
                        else if ($statsName == 'item_sets_tree_edges') {
                            $statsName = $this->translate('Item sets tree edges');
                        }
                        else if ($statsName == 'uris') {
                            $statsName = $this->translate('uris');
                        }
                    ?>
                    <li><?php echo $escape(sprintf('%s: %d %s',
                        $this->translate(ucfirst($this->translate($isUpdate ? 'updated' : 'added'))),
                        $stat, ucfirst($statsName))); ?></li>
                <?php endforeach; ?>
                </ul>
            </td>
            <td>
            <?php if ($undoJob):
                if ($undoJob->ended()):
                    echo $escape(sprintf($this->translate('Undone %s'), $this->i18n()->dateFormat($undoJob->ended())));
                ?>
                <?php
                else:
                    echo $escape($this->translate('Undo in progress'));
                endif;
                ?>
                <br />
                <span class="from-classicwith-love-job-param">
                    <?php echo $this->hyperlink($this->translate('Job details'), $this->url('admin/id', ['controller' => 'job', 'action' => 'show', 'id' => $undoJob->id()])); ?>
                </span>
                <?php if ($undoJob->log()): ?>
                /
                <span class="from-classicwith-love-job-log">
                    <?php echo $this->hyperlink($this->translate('Log'), $this->url('admin/id', ['controller' => 'job', 'action' => 'log', 'id' => $undoJob->id()]), ['target' => '_blank']); ?>
                </span>
                <?php endif; ?>
            <?php
            else:
                echo ucfirst($escape($this->translate($job->status())));
            endif;
            ?>
            </td>
            <td><?php
            $owner = $job->owner();
            if ($owner):
                echo $this->hyperlink($owner->name(), $this->url('admin/id', array('controller' => 'user', 'action' => 'show', 'id' => $owner->id())));
            endif;
            ?></td>
            <td>
                <?php if (!$isUpdate) {
                    echo $this->hyperlink(
                        ' ' . $this->translate('Update import') . ' ',
                        $this->url('admin/fromclassicwithlove', [], [ 'query' => [ 'jobId' => $job->id() ] ] ),
                        [
                            'controller' => 'item',
                            'action' => 'add',
                            'class' => 'o-icon-upgrade',
                        ],
                    );
                } ?>
            </td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</form>
<?php endif; ?>

<div id="sidebar" class="sidebar">
    <?php echo $this->hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $this->translate('Close'),
    ]); ?>
    <div class="sidebar-content">
    </div>
</div>
